name: Redirect Updater

on:
  schedule:
  - cron:  '30 18 * * *'
  # - cron:  '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    name: run
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'gh-pages'

    - name: Golang Action
      uses: cedrickring/golang-action@1.4.1
  
    - name: Commit files
      run: |
        git config --local user.email "redirects-action@vim-jp.org"
        git config --local user.name "GitHub Action"
        git add --update
        if ! git diff --quiet HEAD ; then
          DATE=$(date "+%Y/%m/%d %H:%M %Z")
          git commit -m "Updated by GithubActions at ${DATE}"    
          git push 
        fi

    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: 'gh-pages'
